spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://metaverse.ohgiraffers.com:3306/cacamuca?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(IU4/9zIakID2tD9DtSw/j10RPubNAzVZ)
    password: ENC(42/QSA+4kQPyK5EXxKmBB0FijMFlNJFT)
    hikari:
      auto-commit: false